[package]
name = "doodle"
version = "0.1.0"
description = "A recursively zoomable creative document"
authors = ["x0bd"]
edition = "2021"

[lib]
name = "doodle_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.3"
sha2 = "0.11.0"
hex = "0.4.3"
base64 = "0.23.1"
